Code Refactor
kathari00/keycloakify-starter-angular pull request #6
Opened 2024-09-14 22:44 UTC by luca-peruzzo

@kathari00 Hi finally here it is the refactor.
Sorry for wasting your time ( :sweat: ) with the previous one, now it works in the keycloak docker container too (tested v23 and v25).
If you have any concerns about this PR please let me know.
Thanks for your time!

[I will leave this PR in draft untill your approval]

2024-09-14 22:59 UTC, kathari00 commented
Hi thanks for checking in. Does the navigation work as well?

What about the locale mode does it start up?

2024-09-14 23:04 UTC, luca-peruzzo commented
Yes for both, there is only some warnings on the keycloakify generated assets (some .eot fonts missing) but it compiles and shows the page

2024-09-14 23:12 UTC, kathari00 commented on src/keycloak-theme/keycloak-context.provider.ts
I would rather put the providers under common

2024-09-14 23:17 UTC, kathari00 requested changes
I want to leave the pipe call wrapped in () as it makes it easier to read for me. 

Thanks for polishing this.

2024-09-15 05:52 UTC, luca-peruzzo commented
> I want to leave the pipe call wrapped in () as it makes it easier to read for me.
> 
> Thanks for polishing this.

What do you mean? could you please reference a piece of code where this wrapping is missing?

2024-09-15 06:49 UTC, kathari00 commented
> > I want to leave the pipe call wrapped in () as it makes it easier to read for me.
> > Thanks for polishing this.
> 
> What do you mean? could you please reference a piece of code where this wrapping is missing?

I want to have it like this
[class]="('sth' | KClass)"

Instead of 
[class]="'sth' | KClass"

2024-09-15 07:18 UTC, luca-peruzzo commented
> > > I want to leave the pipe call wrapped in () as it makes it easier to read for me.
> > > Thanks for polishing this.
> > 
> > 
> > What do you mean? could you please reference a piece of code where this wrapping is missing?
> 
> I want to have it like this [class]="('sth' | KClass)"
> 
> Instead of [class]="'sth' | KClass"

Ok, I think it is an automatic correction of prettier cause brackets aren't necessary. I could check of it is possible to disable this rule

2024-09-15 12:08 UTC, merged